"""add channel fields

Revision ID: 88516fb6ca00
Revises: a8ab46585978
Create Date: 2026-05-13 03:02:50.056221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '88516fb6ca00'
down_revision: Union[str, None] = 'a8ab46585978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
