"""add channel fields

Revision ID: a8ab46585978
Revises: af2e777eb7ea
Create Date: 2026-05-13 03:02:05.542231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8ab46585978'
down_revision: Union[str, None] = 'af2e777eb7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
