"""initial

Revision ID: af2e777eb7ea
Revises: f6072e296415
Create Date: 2026-05-13 03:00:05.156704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'af2e777eb7ea'
down_revision: Union[str, None] = 'f6072e296415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('line_channel_secret', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('line_channel_access_token', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('messenger_page_access_token', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('messenger_verify_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'messenger_verify_token')
    op.drop_column('tenants', 'messenger_page_access_token')
    op.drop_column('tenants', 'line_channel_access_token')
    op.drop_column('tenants', 'line_channel_secret')
    # ### end Alembic commands ###
